### ISSUE TITLE
Issue with runing the QuickStart

### ISSUE THREAD

**Issue by Sadegh-Saberian** [tshauck/gcgc#59]
* GCGC version: 0.12.1
* Python version: 3.6.9
* Operating System: Ubuntu 18.04

### Description
I am trying to replicate the example in the QuickStart...

```
from gcgc import KmerTokenizer

kmer_tokenizer = KmerTokenizer(alphabet="unambiguous_dna")
encoded = kmer_tokenizer.encode("ATCG")
print(encoded)
```

### What I Did

I installed the package and run the following only to get this error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-12027d1b4fb4> in <module>
      1 from gcgc import KmerTokenizer
      2 
----> 3 kmer_tokenizer = KmerTokenizer(alphabet="unambiguous_dna")
      4 encoded = kmer_tokenizer.encode("ATCG")
      5 print(encoded)

TypeError: __init__() got an unexpected keyword argument 'alphabet'
```
I would appreciate your help with this.
thanks!

**Comment by tshauck** [comment]
@Sadegh-Saberian Thanks for filing an issue! Would you mind updating to the latest version and trying again? `pip install -U gcgc`

Please follow up if that doesn't resolve it.

**Comment by Sadegh-Saberian** [comment]
Thanks for your prompt response. I tried it and the issue still is there.

`Requirement already up-to-date: gcgc in ./pytorch/lib/python3.6/site-packages (0.12.1)`

**Comment by tshauck** [comment]
Looks like the root cause is I had changed gcgc to only support python3.7+ (the last to support 3.6 being 0.12.1). I just changed it back to support both. I was able to run that quick start in a fresh 3.6 env, but please give it a shot and lmk (`pip install gcgc==0.13.0`).

**Comment by Sadegh-Saberian** [comment]
That fixed it. thanks!
